"""Initial Impacto schema (PWA build brief §2.1).

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-15 16:03:15.111412
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import impacto.db.types  # EncryptedString / EncryptedNumeric on holdings

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analog_summaries',
    sa.Column('archetype_id', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('window', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('mean_car_bps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('median_car_bps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stdev_bps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hit_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('p5_bps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('p95_bps', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('t_stat', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('p_value', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('analogs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('archetype_id', 'target', 'window', 'as_of')
    )
    with op.batch_alter_table('analog_summaries', schema=None) as batch_op:
        batch_op.create_index('ix_analog_summaries_archetype_target', ['archetype_id', 'target'], unique=False)

    op.create_table('calibration_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('window', sa.String(length=32), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_runs_window'), ['window'], unique=False)

    op.create_table('daily_digests',
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('digest_date')
    )
    op.create_table('detected_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('archetype_id', sa.String(length=64), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('matched_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('surprise_magnitude', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('detected_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detected_events_archetype_id'), ['archetype_id'], unique=False)
        batch_op.create_index('ix_detected_events_date_desc', [sa.literal_column('event_date DESC')], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('compliance_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('used_llm', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_kind'), ['kind'], unique=False)

    op.create_table('holdings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('symbol', impacto.db.types.EncryptedString(), nullable=False),
    sa.Column('weight', impacto.db.types.EncryptedNumeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_user_id'), ['user_id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('ua', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)
        batch_op.create_index('ix_sessions_user_expires', ['user_id', 'expires_at'], unique=False)

    op.create_table('watchlist_archetypes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('archetype_id', sa.String(length=64), nullable=False),
    sa.Column('min_severity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'archetype_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_archetypes')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_expires')
        batch_op.drop_index(batch_op.f('ix_sessions_refresh_token_hash'))

    op.drop_table('sessions')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_user_id'))

    op.drop_table('holdings')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_kind'))
        batch_op.drop_index('ix_audit_log_created_at')

    op.drop_table('audit_log')
    op.drop_table('users')
    with op.batch_alter_table('detected_events', schema=None) as batch_op:
        batch_op.drop_index('ix_detected_events_date_desc')
        batch_op.drop_index(batch_op.f('ix_detected_events_archetype_id'))

    op.drop_table('detected_events')
    op.drop_table('daily_digests')
    with op.batch_alter_table('calibration_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_runs_window'))

    op.drop_table('calibration_runs')
    with op.batch_alter_table('analog_summaries', schema=None) as batch_op:
        batch_op.drop_index('ix_analog_summaries_archetype_target')

    op.drop_table('analog_summaries')
    # ### end Alembic commands ###
